dist: trusty
sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - jdk_switcher use oraclejdk8
  - "wget https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar"
  - "java -jar selenium-server-standalone-3.8.1.jar > /dev/null &"
  - sleep 5
after_success:
  - npm run create-site
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  local_dir: site-dist
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
